// Realistic mock data for LexMeet platform

export const MOCK_DOCUMENTS = [
  {
    id: "doc_001",
    type: "rent_agreement",
    status: "completed",
    userName: "Ramesh Kumar",
    userPhone: "+91 98765 43210",
    propertyAddress: "Flat 402, Sunrise Apartments, Kukatpally, Hyderabad",
    landlordName: "Venkata Rao",
    tenantName: "Ramesh Kumar",
    monthlyRent: 15000,
    deposit: 50000,
    duration: "11 months",
    createdAt: "2024-01-15T10:30:00Z",
    completedAt: "2024-01-15T10:45:00Z",
    advocate: "Adv. Sridhar Sharma",
    eStampNumber: "SHCIL789456123",
  },
  {
    id: "doc_002",
    type: "sale_agreement",
    status: "pending_payment",
    userName: "Lakshmi Devi",
    userPhone: "+91 91234 56789",
    propertyAddress: "Plot 156, Phase 2, Jubilee Hills, Hyderabad",
    sellerName: "Lakshmi Devi",
    buyerName: "Suresh Reddy",
    salePrice: 2500000,
    advanceAmount: 250000,
    createdAt: "2024-01-20T14:15:00Z",
  },
  {
    id: "doc_003",
    type: "will",
    status: "advocate_assigned",
    userName: "Krishna Murthy",
    userPhone: "+91 99887 76655",
    testatorName: "Krishna Murthy",
    executorName: "Vijay Kumar",
    beneficiaries: ["Anitha (Wife)", "Ravi (Son)", "Priya (Daughter)"],
    propertyDetails: "House at Bowenpally, Bank deposits, Gold ornaments",
    createdAt: "2024-01-18T09:00:00Z",
    advocate: "Adv. Padmaja Reddy",
    assignedAt: "2024-01-18T11:30:00Z",
  },
  {
    id: "doc_004",
    type: "power_of_attorney",
    status: "draft",
    userName: "Anil Kumar",
    userPhone: "+91 98888 77777",
    principalName: "Anil Kumar",
    agentName: "Sunil Kumar",
    purpose: "Property management and bank transactions",
    propertyAddress: "Flat 203, Green Valley, Madhapur, Hyderabad",
    createdAt: "2024-01-21T16:20:00Z",
  },
  {
    id: "doc_005",
    type: "rent_agreement",
    status: "advocate_signing",
    userName: "Sunita Sharma",
    userPhone: "+91 97777 88888",
    propertyAddress: "Villa 12, Gated Community, Gachibowli, Hyderabad",
    landlordName: "Sunita Sharma",
    tenantName: "Infosys Technologies Ltd",
    monthlyRent: 45000,
    deposit: 135000,
    duration: "24 months",
    createdAt: "2024-01-19T11:00:00Z",
    advocate: "Adv. Rajesh Gupta",
    eStampNumber: "SHCIL456789012",
  },
  {
    id: "doc_006",
    type: "partnership_deed",
    status: "completed",
    userName: "Praveen & Associates",
    userPhone: "+91 96666 55555",
    firmName: "Praveen & Associates LLP",
    partner1: "Praveen Kumar",
    partner2: "Mahesh Babu",
    businessType: "IT Consulting Services",
    profitSharing: "60:40",
    capitalContribution: 500000,
    createdAt: "2024-01-10T10:00:00Z",
    completedAt: "2024-01-10T11:15:00Z",
    advocate: "Adv. Harish Chandra",
  },
  {
    id: "doc_007",
    type: "legal_notice",
    status: "pending_payment",
    userName: "Geetha Rani",
    userPhone: "+91 95555 44444",
    senderName: "Geetha Rani",
    recipientName: "Raju Constructions Pvt Ltd",
    noticeType: "Breach of Contract",
    issueDescription: "Delayed possession of flat by 18 months",
    reliefSought: "Immediate possession + compensation",
    createdAt: "2024-01-22T09:30:00Z",
  },
  {
    id: "doc_008",
    type: "affidavit",
    status: "draft",
    userName: "Mohammed Ali",
    userPhone: "+91 94444 33333",
    deponentName: "Mohammed Ali",
    affidavitType: "Name Change",
    oldName: "Mohd. Ali Khan",
    newName: "Mohammed Ali",
    reason: "Personal preference and consistency in documents",
    createdAt: "2024-01-21T15:45:00Z",
  },
  {
    id: "doc_009",
    type: "gift_deed",
    status: "advocate_assigned",
    userName: "Ranga Rao",
    userPhone: "+91 93333 22222",
    donorName: "Ranga Rao",
    doneeName: "Lakshmi (Daughter)",
    propertyDescription: "Agricultural land 2 acres at Medchal",
    propertyValue: 800000,
    relationship: "Father to Daughter",
    createdAt: "2024-01-17T14:00:00Z",
    advocate: "Adv. Srinivas Reddy",
    assignedAt: "2024-01-17T16:30:00Z",
  },
  {
    id: "doc_010",
    type: "rent_agreement",
    status: "completed",
    userName: "Priya Patel",
    userPhone: "+91 92222 11111",
    propertyAddress: "303, Cyber Towers, Hitech City, Hyderabad",
    landlordName: "Priya Patel",
    tenantName: "Startup Hub Pvt Ltd",
    monthlyRent: 35000,
    deposit: 105000,
    duration: "12 months",
    createdAt: "2024-01-12T10:30:00Z",
    completedAt: "2024-01-12T10:50:00Z",
    advocate: "Adv. Kavita Sharma",
    eStampNumber: "SHCIL123456789",
  },
  {
    id: "doc_011",
    type: "nda",
    status: "pending_payment",
    userName: "TechStart Solutions",
    userPhone: "+91 91111 00000",
    companyName: "TechStart Solutions Pvt Ltd",
    counterpartyName: "Investor Group XYZ",
    ndaType: "Mutual NDA",
    purpose: "Due diligence for Series A funding",
    validityPeriod: "3 years",
    createdAt: "2024-01-23T11:00:00Z",
  },
  {
    id: "doc_012",
    type: "offer_letter",
    status: "completed",
    userName: "Global IT Services",
    userPhone: "+91 90000 99999",
    companyName: "Global IT Services Ltd",
    candidateName: "Ravi Teja",
    position: "Senior Software Engineer",
    joiningDate: "2024-02-15",
    ctc: 1800000,
    location: "Hyderabad",
    createdAt: "2024-01-14T09:00:00Z",
    completedAt: "2024-01-14T09:20:00Z",
  },
  {
    id: "doc_013",
    type: "loan_agreement",
    status: "advocate_signing",
    userName: "Vijay Kumar",
    userPhone: "+91 88888 77777",
    lenderName: "Vijay Kumar",
    borrowerName: "Srinivas Reddy",
    loanAmount: 500000,
    interestRate: 12,
    duration: "24 months",
    createdAt: "2024-01-20T16:00:00Z",
    advocate: "Adv. Suresh Babu",
  },
  {
    id: "doc_014",
    type: "divorce_settlement",
    status: "draft",
    userName: "Anitha Reddy",
    userPhone: "+91 87777 66666",
    husbandName: "Srinivas Reddy",
    wifeName: "Anitha Reddy",
    marriageDate: "2015-06-15",
    children: ["Arjun (8 years)"],
    alimonyAmount: 50000,
    propertyDivision: "House to wife, Car to husband",
    createdAt: "2024-01-21T11:30:00Z",
  },
  {
    id: "doc_015",
    type: "lease_agreement",
    status: "completed",
    userName: "Commercial Properties Ltd",
    userPhone: "+91 86666 55555",
    propertyAddress: "Shop 12, Central Mall, Banjara Hills, Hyderabad",
    lessorName: "Commercial Properties Ltd",
    lesseeName: "Fashion Retail India",
    monthlyRent: 75000,
    leaseTerm: "5 years",
    securityDeposit: 225000,
    createdAt: "2024-01-08T10:00:00Z",
    completedAt: "2024-01-08T10:30:00Z",
    advocate: "Adv. Meera Nair",
  },
  {
    id: "doc_016",
    type: "rent_agreement",
    status: "pending_payment",
    userName: "Kiran Kumar",
    userPhone: "+91 85555 44444",
    propertyAddress: "Flat 501, Lakeview Apartments, Secunderabad",
    landlordName: "Kiran Kumar",
    tenantName: "Divya Sharma",
    monthlyRent: 20000,
    deposit: 60000,
    duration: "11 months",
    createdAt: "2024-01-23T14:00:00Z",
  },
  {
    id: "doc_017",
    type: "trust_deed",
    status: "advocate_assigned",
    userName: "Chandra Shekar",
    userPhone: "+91 84444 33333",
    trustName: "Chandra Educational Trust",
    settlorName: "Chandra Shekar",
    trustees: ["Venkatesh", "Sarala Devi"],
    beneficiaries: ["Underprivileged students"],
    trustProperty: "Land 1 acre at Shamshabad, Cash 50 Lakhs",
    createdAt: "2024-01-16T09:15:00Z",
    advocate: "Adv. Gopal Krishna",
    assignedAt: "2024-01-16T11:45:00Z",
  },
  {
    id: "doc_018",
    type: "memorandum_of_understanding",
    status: "draft",
    userName: "MediCare Hospitals",
    userPhone: "+91 83333 22222",
    partyA: "MediCare Hospitals Pvt Ltd",
    partyB: "PharmaCorp India Ltd",
    purpose: "Strategic partnership for medical supplies",
    duration: "3 years",
    keyTerms: ["Exclusive supply agreement", "Volume discounts", "Quality standards"],
    createdAt: "2024-01-22T16:30:00Z",
  },
  {
    id: "doc_019",
    type: "promissory_note",
    status: "completed",
    userName: "Ganesh Enterprises",
    userPhone: "+91 82222 11111",
    makerName: "Ganesh Enterprises",
    payeeName: "Bank of India",
    amount: 1000000,
    interestRate: 10.5,
    dueDate: "2025-01-20",
    purpose: "Working capital loan",
    createdAt: "2024-01-13T11:00:00Z",
    completedAt: "2024-01-13T11:25:00Z",
  },
  {
    id: "doc_020",
    type: "rent_agreement",
    status: "advocate_signing",
    userName: "Padmaja Reddy",
    userPhone: "+91 81111 00000",
    propertyAddress: "House 45, Defence Colony, Sainikpuri, Hyderabad",
    landlordName: "Padmaja Reddy",
    tenantName: "Dr. Reddy's Laboratories",
    monthlyRent: 60000,
    deposit: 180000,
    duration: "24 months",
    createdAt: "2024-01-19T15:00:00Z",
    advocate: "Adv. Venkat Ram",
    eStampNumber: "SHCIL987654321",
  },
];

export const MOCK_LAWYERS = [
  {
    id: "lawyer_001",
    name: "Adv. Sridhar Sharma",
    phone: "+91 98765 12345",
    email: "sridhar.sharma@lexmeet.in",
    barCouncilNumber: "TS/1234/2015",
    specialization: ["Property Law", "Civil Law"],
    experience: 12,
    rating: 4.8,
    totalCases: 450,
    location: "Hyderabad",
    address: "123, Legal Chambers, High Court Road, Hyderabad",
    languages: ["Telugu", "English", "Hindi"],
    isVerified: true,
    isAvailable: true,
    photo: "/lawyers/sridhar.jpg",
    bio: "Specialist in property disputes and rental agreements with 12+ years experience.",
  },
  {
    id: "lawyer_002",
    name: "Adv. Padmaja Reddy",
    phone: "+91 98765 23456",
    email: "padmaja.reddy@lexmeet.in",
    barCouncilNumber: "TS/2345/2010",
    specialization: ["Family Law", "Wills & Trusts"],
    experience: 18,
    rating: 4.9,
    totalCases: 320,
    location: "Hyderabad",
    address: "456, Family Court Complex, Hyderabad",
    languages: ["Telugu", "English"],
    isVerified: true,
    isAvailable: true,
    photo: "/lawyers/padmaja.jpg",
    bio: "Expert in family matters, divorce settlements, and estate planning.",
  },
  {
    id: "lawyer_003",
    name: "Adv. Rajesh Gupta",
    phone: "+91 98765 34567",
    email: "rajesh.gupta@lexmeet.in",
    barCouncilNumber: "TS/3456/2012",
    specialization: ["Corporate Law", "Contracts"],
    experience: 15,
    rating: 4.7,
    totalCases: 280,
    location: "Hyderabad",
    address: "789, Business District, Gachibowli, Hyderabad",
    languages: ["English", "Hindi", "Telugu"],
    isVerified: true,
    isAvailable: false,
    photo: "/lawyers/rajesh.jpg",
    bio: "Corporate lawyer specializing in business contracts and commercial disputes.",
  },
  {
    id: "lawyer_004",
    name: "Adv. Harish Chandra",
    phone: "+91 98765 45678",
    email: "harish.chandra@lexmeet.in",
    barCouncilNumber: "TS/4567/2008",
    specialization: ["Criminal Law", "Civil Law"],
    experience: 20,
    rating: 4.8,
    totalCases: 600,
    location: "Secunderabad",
    address: "321, Criminal Court Complex, Secunderabad",
    languages: ["Telugu", "English", "Hindi"],
    isVerified: true,
    isAvailable: true,
    photo: "/lawyers/harish.jpg",
    bio: "Criminal defense attorney with extensive trial experience.",
  },
  {
    id: "lawyer_005",
    name: "Adv. Kavita Sharma",
    phone: "+91 98765 56789",
    email: "kavita.sharma@lexmeet.in",
    barCouncilNumber: "TS/5678/2016",
    specialization: ["Property Law", "Rental Agreements"],
    experience: 10,
    rating: 4.6,
    totalCases: 380,
    location: "Hyderabad",
    address: "654, Property Law Center, Kukatpally, Hyderabad",
    languages: ["Telugu", "English"],
    isVerified: true,
    isAvailable: true,
    photo: "/lawyers/kavita.jpg",
    bio: "Focused on rental agreements and landlord-tenant disputes.",
  },
  {
    id: "lawyer_006",
    name: "Adv. Srinivas Reddy",
    phone: "+91 98765 67890",
    email: "srinivas.reddy@lexmeet.in",
    barCouncilNumber: "TS/6789/2014",
    specialization: ["Land Law", "Agricultural Property"],
    experience: 14,
    rating: 4.7,
    totalCases: 290,
    location: "Warangal",
    address: "987, District Court Road, Warangal",
    languages: ["Telugu", "English"],
    isVerified: true,
    isAvailable: true,
    photo: "/lawyers/srinivas.jpg",
    bio: "Expert in agricultural land transactions and rural property law.",
  },
  {
    id: "lawyer_007",
    name: "Adv. Meera Nair",
    phone: "+91 98765 78901",
    email: "meera.nair@lexmeet.in",
    barCouncilNumber: "TS/7890/2013",
    specialization: ["Corporate Law", "IP Law"],
    experience: 13,
    rating: 4.9,
    totalCases: 340,
    location: "Hyderabad",
    address: "147, Hitech City, Hyderabad",
    languages: ["English", "Malayalam", "Telugu"],
    isVerified: true,
    isAvailable: true,
    photo: "/lawyers/meera.jpg",
    bio: "IP and corporate lawyer with expertise in technology contracts.",
  },
  {
    id: "lawyer_008",
    name: "Adv. Suresh Babu",
    phone: "+91 98765 89012",
    email: "suresh.babu@lexmeet.in",
    barCouncilNumber: "TS/8901/2011",
    specialization: ["Banking Law", "Financial Agreements"],
    experience: 17,
    rating: 4.8,
    totalCases: 410,
    location: "Hyderabad",
    address: "258, Financial District, Hyderabad",
    languages: ["Telugu", "English", "Hindi"],
    isVerified: true,
    isAvailable: false,
    photo: "/lawyers/suresh.jpg",
    bio: "Banking specialist handling loan agreements and financial disputes.",
  },
  {
    id: "lawyer_009",
    name: "Adv. Gopal Krishna",
    phone: "+91 98765 90123",
    email: "gopal.krishna@lexmeet.in",
    barCouncilNumber: "TS/9012/2009",
    specialization: ["Constitutional Law", "Civil Rights"],
    experience: 19,
    rating: 4.9,
    totalCases: 280,
    location: "Hyderabad",
    address: "369, High Court Area, Hyderabad",
    languages: ["Telugu", "English", "Sanskrit"],
    isVerified: true,
    isAvailable: true,
    photo: "/lawyers/gopal.jpg",
    bio: "Constitutional expert handling PILs and civil rights cases.",
  },
  {
    id: "lawyer_010",
    name: "Adv. Venkat Ram",
    phone: "+91 98765 01234",
    email: "venkat.ram@lexmeet.in",
    barCouncilNumber: "TS/0123/2017",
    specialization: ["Property Law", "Documentation"],
    experience: 9,
    rating: 4.5,
    totalCases: 250,
    location: "Hyderabad",
    address: "741, Document Center, Ameerpet, Hyderabad",
    languages: ["Telugu", "English"],
    isVerified: true,
    isAvailable: true,
    photo: "/lawyers/venkat.jpg",
    bio: "Young advocate specializing in property documentation.",
  },
  {
    id: "lawyer_011",
    name: "Adv. Lakshmi Narayana",
    phone: "+91 98766 12345",
    email: "lakshmi.narayana@lexmeet.in",
    barCouncilNumber: "TS/1123/2012",
    specialization: ["Tax Law", "Corporate Law"],
    experience: 16,
    rating: 4.7,
    totalCases: 360,
    location: "Hyderabad",
    address: "852, Tax Tower, Begumpet, Hyderabad",
    languages: ["Telugu", "English", "Hindi"],
    isVerified: true,
    isAvailable: true,
    photo: "/lawyers/lakshmi.jpg",
    bio: "Tax and corporate compliance specialist.",
  },
  {
    id: "lawyer_012",
    name: "Adv. Anitha Devi",
    phone: "+91 98766 23456",
    email: "anitha.devi@lexmeet.in",
    barCouncilNumber: "TS/2234/2015",
    specialization: ["Family Law", "Women's Rights"],
    experience: 11,
    rating: 4.8,
    totalCases: 290,
    location: "Hyderabad",
    address: "963, Women's Legal Aid Center, Hyderabad",
    languages: ["Telugu", "English", "Hindi"],
    isVerified: true,
    isAvailable: true,
    photo: "/lawyers/anitha.jpg",
    bio: "Advocate for women's rights and family law matters.",
  },
  {
    id: "lawyer_013",
    name: "Adv. Ravi Teja",
    phone: "+91 98766 34567",
    email: "ravi.teja@lexmeet.in",
    barCouncilNumber: "TS/3345/2018",
    specialization: ["Startup Law", "Technology"],
    experience: 7,
    rating: 4.6,
    totalCases: 180,
    location: "Hyderabad",
    address: "159, Startup Hub, Hitech City, Hyderabad",
    languages: ["English", "Telugu"],
    isVerified: true,
    isAvailable: true,
    photo: "/lawyers/ravi.jpg",
    bio: "Young lawyer focused on startups and technology law.",
  },
  {
    id: "lawyer_014",
    name: "Adv. Sarala Devi",
    phone: "+91 98766 45678",
    email: "sarala.devi@lexmeet.in",
    barCouncilNumber: "TS/4456/2007",
    specialization: ["Succession Law", "Wills"],
    experience: 21,
    rating: 4.9,
    totalCases: 420,
    location: "Hyderabad",
    address: "357, Estate Planning Center, Jubilee Hills, Hyderabad",
    languages: ["Telugu", "English", "Hindi"],
    isVerified: true,
    isAvailable: false,
    photo: "/lawyers/sarala.jpg",
    bio: "Estate planning and succession law expert.",
  },
  {
    id: "lawyer_015",
    name: "Adv. Krishnam Raju",
    phone: "+91 98766 56789",
    email: "krishnam.raju@lexmeet.in",
    barCouncilNumber: "TS/5567/2010",
    specialization: ["Labor Law", "Employment"],
    experience: 18,
    rating: 4.7,
    totalCases: 310,
    location: "Hyderabad",
    address: "486, Labour Court Area, Hyderabad",
    languages: ["Telugu", "English", "Hindi"],
    isVerified: true,
    isAvailable: true,
    photo: "/lawyers/krishnam.jpg",
    bio: "Labor law specialist handling employment disputes and contracts.",
  },
];

export const MOCK_WAITLIST = [
  { id: "wl_001", name: "Venkat Reddy", phone: "+91 98888 11111", city: "Hyderabad", documentType: "Property Registration", signupDate: "2024-01-15", source: "Facebook" },
  { id: "wl_002", name: "Sunitha Devi", phone: "+91 98888 22222", city: "Vijayawada", documentType: "Will", signupDate: "2024-01-16", source: "Google" },
  { id: "wl_003", name: "Mohan Kumar", phone: "+91 98888 33333", city: "Warangal", documentType: "Rent Agreement", signupDate: "2024-01-16", source: "Referral" },
  { id: "wl_004", name: "Lakshmi Patel", phone: "+91 98888 44444", city: "Guntur", documentType: "Sale Deed", signupDate: "2024-01-17", source: "Instagram" },
  { id: "wl_005", name: "Krishna Murthy", phone: "+91 98888 55555", city: "Hyderabad", documentType: "Legal Notice", signupDate: "2024-01-17", source: "Facebook" },
  { id: "wl_006", name: "Padmavathi", phone: "+91 98888 66666", city: "Nellore", documentType: "Gift Deed", signupDate: "2024-01-18", source: "Google" },
  { id: "wl_007", name: "Ravi Shankar", phone: "+91 98888 77777", city: "Kakinada", documentType: "Partnership Deed", signupDate: "2024-01-18", source: "LinkedIn" },
  { id: "wl_008", name: "Anuradha", phone: "+91 98888 88888", city: "Hyderabad", documentType: "Divorce Agreement", signupDate: "2024-01-19", source: "Referral" },
  { id: "wl_009", name: "Prakash Rao", phone: "+91 98888 99999", city: "Rajahmundry", documentType: "Power of Attorney", signupDate: "2024-01-19", source: "Facebook" },
  { id: "wl_010", name: "Savitri Devi", phone: "+91 97777 11111", city: "Karimnagar", documentType: "Affidavit", signupDate: "2024-01-20", source: "Google" },
  { id: "wl_011", name: "Gopal Reddy", phone: "+91 97777 22222", city: "Hyderabad", documentType: "Trust Deed", signupDate: "2024-01-20", source: "Instagram" },
  { id: "wl_012", name: "Radha Krishna", phone: "+91 97777 33333", city: "Nizamabad", documentType: "Rent Agreement", signupDate: "2024-01-21", source: "Facebook" },
  { id: "wl_013", name: "Seetha Lakshmi", phone: "+91 97777 44444", city: "Khammam", documentType: "Sale Deed", signupDate: "2024-01-21", source: "Google" },
  { id: "wl_014", name: "Narasimha Rao", phone: "+91 97777 55555", city: "Hyderabad", documentType: "Legal Notice", signupDate: "2024-01-22", source: "Referral" },
  { id: "wl_015", name: "Vijaya Lakshmi", phone: "+91 97777 66666", city: "Ongole", documentType: "Property Partition", signupDate: "2024-01-22", source: "Facebook" },
  { id: "wl_016", name: "Srinivas Reddy", phone: "+91 97777 77777", city: "Tirupati", documentType: "Will", signupDate: "2024-01-23", source: "Google" },
  { id: "wl_017", name: "Kamala Devi", phone: "+91 97777 88888", city: "Hyderabad", documentType: "Gift Deed", signupDate: "2024-01-23", source: "Instagram" },
  { id: "wl_018", name: "Bharath Kumar", phone: "+91 97777 99999", city: "Anantapur", documentType: "Rent Agreement", signupDate: "2024-01-24", source: "Facebook" },
  { id: "wl_019", name: "Uma Maheshwari", phone: "+91 96666 11111", city: "Hyderabad", documentType: "Partnership Deed", signupDate: "2024-01-24", source: "LinkedIn" },
  { id: "wl_020", name: "Chandra Shekar", phone: "+91 96666 22222", city: "Kurnool", documentType: "Power of Attorney", signupDate: "2024-01-25", source: "Google" },
  { id: "wl_021", name: "Manjula Rani", phone: "+91 96666 33333", city: "Eluru", documentType: "Divorce Settlement", signupDate: "2024-01-25", source: "Facebook" },
  { id: "wl_022", name: "Jagadish Prasad", phone: "+91 96666 44444", city: "Hyderabad", documentType: "Lease Agreement", signupDate: "2024-01-26", source: "Referral" },
  { id: "wl_023", name: "Satya Narayana", phone: "+91 96666 55555", city: "Machilipatnam", documentType: "Property Registration", signupDate: "2024-01-26", source: "Google" },
  { id: "wl_024", name: "Saraswathi Devi", phone: "+91 96666 66666", city: "Hyderabad", documentType: "Affidavit", signupDate: "2024-01-27", source: "Instagram" },
  { id: "wl_025", name: "Venkateshwarlu", phone: "+91 96666 77777", city: "Adoni", documentType: "Sale Deed", signupDate: "2024-01-27", source: "Facebook" },
  { id: "wl_026", name: "Bhavani Shankar", phone: "+91 96666 88888", city: "Proddatur", documentType: "Rent Agreement", signupDate: "2024-01-28", source: "Google" },
  { id: "wl_027", name: "Sree Lakshmi", phone: "+91 96666 99999", city: "Hyderabad", documentType: "Legal Notice", signupDate: "2024-01-28", source: "Referral" },
  { id: "wl_028", name: "Rama Krishna", phone: "+91 95555 11111", city: "Tenali", documentType: "Trust Deed", signupDate: "2024-01-29", source: "Facebook" },
  { id: "wl_029", name: "Annapurna Devi", phone: "+91 95555 22222", city: "Chittoor", documentType: "Will", signupDate: "2024-01-29", source: "Google" },
  { id: "wl_030", name: "Siva Prasad", phone: "+91 95555 33333", city: "Hyderabad", documentType: "Gift Deed", signupDate: "2024-01-30", source: "Instagram" },
  { id: "wl_031", name: "Durga Devi", phone: "+91 95555 44444", city: "Srikakulam", documentType: "Property Partition", signupDate: "2024-01-30", source: "Facebook" },
  { id: "wl_032", name: "Nagendra Rao", phone: "+91 95555 55555", city: "Hyderabad", documentType: "Partnership Deed", signupDate: "2024-01-31", source: "LinkedIn" },
  { id: "wl_033", name: "Parvathi", phone: "+91 95555 66666", city: "Bhimavaram", documentType: "Power of Attorney", signupDate: "2024-01-31", source: "Google" },
  { id: "wl_034", name: "Seshagiri Rao", phone: "+91 95555 77777", city: "Hyderabad", documentType: "Affidavit", signupDate: "2024-02-01", source: "Facebook" },
  { id: "wl_035", name: "Vasundhara", phone: "+91 95555 88888", city: "Madanapalle", documentType: "Rent Agreement", signupDate: "2024-02-01", source: "Referral" },
  { id: "wl_036", name: "Yogendra Nath", phone: "+91 95555 99999", city: "Hyderabad", documentType: "Sale Deed", signupDate: "2024-02-02", source: "Google" },
  { id: "wl_037", name: "Rajya Lakshmi", phone: "+91 94444 11111", city: "Nandyal", documentType: "Legal Notice", signupDate: "2024-02-02", source: "Instagram" },
  { id: "wl_038", name: "Surya Prakash", phone: "+91 94444 22222", city: "Hyderabad", documentType: "Lease Agreement", signupDate: "2024-02-03", source: "Facebook" },
  { id: "wl_039", name: "Madhavi Latha", phone: "+91 94444 33333", city: "Mahabubnagar", documentType: "Property Registration", signupDate: "2024-02-03", source: "Google" },
  { id: "wl_040", name: "Ganesh Kumar", phone: "+91 94444 44444", city: "Hyderabad", documentType: "Will", signupDate: "2024-02-04", source: "Facebook" },
  { id: "wl_041", name: "Indira Devi", phone: "+91 94444 55555", city: "Hindupur", documentType: "Gift Deed", signupDate: "2024-02-04", source: "Referral" },
  { id: "wl_042", name: "Sudhakar Reddy", phone: "+91 94444 66666", city: "Hyderabad", documentType: "Rent Agreement", signupDate: "2024-02-05", source: "Google" },
  { id: "wl_043", name: "Vani Sree", phone: "+91 94444 77777", city: "Siddipet", documentType: "Divorce Settlement", signupDate: "2024-02-05", source: "Instagram" },
  { id: "wl_044", name: "Murali Krishna", phone: "+91 94444 88888", city: "Hyderabad", documentType: "Trust Deed", signupDate: "2024-02-06", source: "Facebook" },
  { id: "wl_045", name: "Lalitha Devi", phone: "+91 94444 99999", city: "Jagtial", documentType: "Power of Attorney", signupDate: "2024-02-06", source: "Google" },
  { id: "wl_046", name: "Venu Gopal", phone: "+91 93333 11111", city: "Hyderabad", documentType: "Sale Deed", signupDate: "2024-02-07", source: "LinkedIn" },
  { id: "wl_047", name: "Hema Latha", phone: "+91 93333 22222", city: "Miryalaguda", documentType: "Legal Notice", signupDate: "2024-02-07", source: "Facebook" },
  { id: "wl_048", name: "Srihari Prasad", phone: "+91 93333 33333", city: "Hyderabad", documentType: "Partnership Deed", signupDate: "2024-02-08", source: "Referral" },
  { id: "wl_049", name: "Swathi Reddy", phone: "+91 93333 44444", city: "Suryapet", documentType: "Property Partition", signupDate: "2024-02-08", source: "Google" },
  { id: "wl_050", name: "Pradeep Kumar", phone: "+91 93333 55555", city: "Hyderabad", documentType: "Affidavit", signupDate: "2024-02-09", source: "Facebook" },
];

// Stats for admin dashboard
export const MOCK_STATS = {
  totalDocuments: 1247,
  completedDocuments: 892,
  pendingPayment: 145,
  advocateAssigned: 210,
  totalLawyers: 342,
  verifiedLawyers: 298,
  availableLawyers: 156,
  totalWaitlist: 2847,
  todaySignups: 23,
  todayRevenue: 45600,
  monthlyRevenue: 1245800,
  conversionRate: 68.5,
  avgRating: 4.8,
};

// Helper functions
export function getStatusColor(status: string): string {
  const colors: Record<string, string> = {
    draft: "bg-slate-100 text-slate-700",
    pending_payment: "bg-orange-100 text-orange-700",
    advocate_assigned: "bg-blue-100 text-blue-700",
    advocate_signing: "bg-purple-100 text-purple-700",
    user_signing: "bg-yellow-100 text-yellow-700",
    completed: "bg-green-100 text-green-700",
    cancelled: "bg-red-100 text-red-700",
  };
  return colors[status] || "bg-slate-100 text-slate-700";
}

export function getStatusLabel(status: string, isTelugu: boolean): string {
  const labels: Record<string, { te: string; en: string }> = {
    draft: { te: "డ్రాఫ్ట్", en: "Draft" },
    pending_payment: { te: "చెల్లింపు కావాలి", en: "Payment Pending" },
    advocate_assigned: { te: "న్యాయవాది కేటాయించబడింది", en: "Advocate Assigned" },
    advocate_signing: { te: "న్యాయవాది సంతకం", en: "Advocate Signing" },
    user_signing: { te: "వినియోగదారు సంతకం", en: "User Signing" },
    completed: { te: "పూర్తయింది", en: "Completed" },
    cancelled: { te: "రద్దు", en: "Cancelled" },
  };
  return labels[status]?.[isTelugu ? "te" : "en"] || status;
}

export function formatCurrency(amount: number): string {
  return new Intl.NumberFormat("en-IN", {
    style: "currency",
    currency: "INR",
    maximumFractionDigits: 0,
  }).format(amount);
}

export function formatDate(dateString: string): string {
  return new Date(dateString).toLocaleDateString("en-IN", {
    year: "numeric",
    month: "short",
    day: "numeric",
  });
}
