import { jsPDF } from "jspdf";

export function generatePDF(content: string, title: string): Blob {
  const doc = new jsPDF();
  
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 25.4; // 1 inch in mm
  const contentWidth = pageWidth - 2 * margin;
  
  let pageNumber = 1;
  
  // Header
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text(title.toUpperCase(), pageWidth / 2, margin + 10, { align: "center" });
  
  // Body text
  doc.setFont("helvetica", "normal");
  doc.setFontSize(12);
  
  const lines = doc.splitTextToSize(content, contentWidth);
  let y = margin + 25;
  const lineHeight = 7.5; // Better spacing for larger font
  
  for (let i = 0; i < lines.length; i++) {
    // Check if we need a new page
    if (y > pageHeight - margin - 20) {
      // Add footer to current page
      addFooter(doc, pageNumber, pageWidth, pageHeight, margin);
      
      doc.addPage();
      pageNumber++;
      y = margin + 10;
      
      // Add header to new page
      doc.setFont("helvetica", "bold");
      doc.setFontSize(16);
      doc.text(title.toUpperCase(), pageWidth / 2, margin, { align: "center" });
      doc.setFont("helvetica", "normal");
      doc.setFontSize(12);
      y = margin + 15;
    }
    
    doc.text(lines[i], margin, y);
    y += lineHeight;
  }
  
  // Add footer to last page
  addFooter(doc, pageNumber, pageWidth, pageHeight, margin);
  
  return doc.output("blob");
}

function addFooter(
  doc: jsPDF, 
  pageNumber: number, 
  pageWidth: number, 
  pageHeight: number, 
  margin: number
) {
  const footerY = pageHeight - margin + 5;
  
  // Page number
  doc.setFontSize(10);
  doc.text(`Page ${pageNumber}`, pageWidth / 2, footerY, { align: "center" });
  
  // Disclaimer
  doc.setFontSize(9);
  doc.setTextColor(100, 100, 100);
  const disclaimer = "Generated by PaperWise | Not a substitute for professional legal advice";
  doc.text(disclaimer, pageWidth / 2, footerY + 5, { align: "center" });
  doc.setTextColor(0, 0, 0);
}

export function downloadPDF(blob: Blob, filename: string) {
  const url = window.URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  window.URL.revokeObjectURL(url);
}
