import { jsPDF } from "jspdf";

export type PDFFont = "helvetica" | "times" | "courier";

export interface PDFOptions {
  font?: PDFFont;
  fontSize?: number;
  lineHeight?: number;
}

export function generatePDF(
  content: string, 
  title: string, 
  options: PDFOptions = {}
): Blob {
  const {
    font = "helvetica",
    fontSize = 14,
    lineHeight: customLineHeight
  } = options;
  
  const doc = new jsPDF();
  
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20; // Slightly smaller margin for more content
  const contentWidth = pageWidth - 2 * margin;
  
  let pageNumber = 1;
  
  // Calculate line height based on font size
  const lineHeight = customLineHeight || (fontSize * 0.5);
  const headerFontSize = fontSize + 4;
  const bodyFontSize = fontSize;
  const subHeaderFontSize = fontSize + 2;
  
  // Header
  doc.setFont(font, "bold");
  doc.setFontSize(headerFontSize);
  doc.text(title.toUpperCase(), pageWidth / 2, margin + 10, { align: "center" });
  
  // Body text
  doc.setFont(font, "normal");
  doc.setFontSize(bodyFontSize);
  
  const lines = doc.splitTextToSize(content, contentWidth);
  let y = margin + 25;
  
  for (let i = 0; i < lines.length; i++) {
    // Check if we need a new page
    if (y > pageHeight - margin - 20) {
      // Add footer to current page
      addFooter(doc, pageNumber, pageWidth, pageHeight, margin, bodyFontSize);
      
      doc.addPage();
      pageNumber++;
      y = margin + 10;
      
      // Add header to new page
      doc.setFont(font, "bold");
      doc.setFontSize(subHeaderFontSize);
      doc.text(title.toUpperCase(), pageWidth / 2, margin, { align: "center" });
      doc.setFont(font, "normal");
      doc.setFontSize(bodyFontSize);
      y = margin + 15;
    }
    
    doc.text(lines[i], margin, y);
    y += lineHeight;
  }
  
  // Add footer to last page
  addFooter(doc, pageNumber, pageWidth, pageHeight, margin, bodyFontSize);
  
  return doc.output("blob");
}

function addFooter(
  doc: jsPDF, 
  pageNumber: number, 
  pageWidth: number, 
  pageHeight: number, 
  margin: number,
  fontSize: number = 14
) {
  const footerY = pageHeight - margin + 5;
  
  // Page number
  doc.setFontSize(Math.max(10, fontSize - 2));
  doc.text(`Page ${pageNumber}`, pageWidth / 2, footerY, { align: "center" });
  
  // Disclaimer
  doc.setFontSize(Math.max(9, fontSize - 3));
  doc.setTextColor(100, 100, 100);
  const disclaimer = "Generated by PaperWise | Not a substitute for professional legal advice";
  doc.text(disclaimer, pageWidth / 2, footerY + 5, { align: "center" });
  doc.setTextColor(0, 0, 0);
}

export function downloadPDF(blob: Blob, filename: string) {
  const url = window.URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  window.URL.revokeObjectURL(url);
}
