import { jsPDF } from "jspdf";
import QRCode from "qrcode";
import { createHash } from "crypto";

export type PDFFont = "helvetica" | "times" | "courier";

export interface PDFOptions {
  font?: PDFFont;
  fontSize?: number;
  lineHeight?: number;
  documentId?: string;
  blockchainHash?: string;
  signedBy?: string;
  signedAt?: string;
  addVerificationQR?: boolean;
}

export function generatePDF(
  content: string, 
  title: string, 
  options: PDFOptions = {}
): Blob {
  const {
    font = "helvetica",
    fontSize = 14,
    lineHeight: customLineHeight
  } = options;
  
  const doc = new jsPDF();
  
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20; // Slightly smaller margin for more content
  const contentWidth = pageWidth - 2 * margin;
  
  let pageNumber = 1;
  
  // Calculate line height based on font size
  const lineHeight = customLineHeight || (fontSize * 0.5);
  const headerFontSize = fontSize + 4;
  const bodyFontSize = fontSize;
  const subHeaderFontSize = fontSize + 2;
  
  // Header
  doc.setFont(font, "bold");
  doc.setFontSize(headerFontSize);
  doc.text(title.toUpperCase(), pageWidth / 2, margin + 10, { align: "center" });
  
  // Body text
  doc.setFont(font, "normal");
  doc.setFontSize(bodyFontSize);
  
  const lines = doc.splitTextToSize(content, contentWidth);
  let y = margin + 25;
  
  for (let i = 0; i < lines.length; i++) {
    // Check if we need a new page
    if (y > pageHeight - margin - 20) {
      // Add footer to current page
      addFooter(doc, pageNumber, pageWidth, pageHeight, margin, bodyFontSize);
      
      doc.addPage();
      pageNumber++;
      y = margin + 10;
      
      // Add header to new page
      doc.setFont(font, "bold");
      doc.setFontSize(subHeaderFontSize);
      doc.text(title.toUpperCase(), pageWidth / 2, margin, { align: "center" });
      doc.setFont(font, "normal");
      doc.setFontSize(bodyFontSize);
      y = margin + 15;
    }
    
    doc.text(lines[i], margin, y);
    y += lineHeight;
  }
  
  // Add footer to last page
  addFooter(doc, pageNumber, pageWidth, pageHeight, margin, bodyFontSize);
  
  return doc.output("blob");
}

function addFooter(
  doc: jsPDF, 
  pageNumber: number, 
  pageWidth: number, 
  pageHeight: number, 
  margin: number,
  fontSize: number = 14
) {
  const footerY = pageHeight - margin + 5;
  
  // Page number
  doc.setFontSize(Math.max(10, fontSize - 2));
  doc.text(`Page ${pageNumber}`, pageWidth / 2, footerY, { align: "center" });
  
  // Disclaimer
  doc.setFontSize(Math.max(9, fontSize - 3));
  doc.setTextColor(100, 100, 100);
  const disclaimer = "Generated by Sakshi.ai — India's Legal Witness | Not a substitute for professional legal advice";
  doc.text(disclaimer, pageWidth / 2, footerY + 5, { align: "center" });
  doc.setTextColor(0, 0, 0);
}

export function downloadPDF(blob: Blob, filename: string) {
  const url = window.URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  window.URL.revokeObjectURL(url);
}

/**
 * Generate SHA-256 hash for document verification
 */
export function generateDocumentHash(
  documentId: string,
  content: string,
  lawyerSignature: string,
  timestamp: string
): string {
  const hashInput = `${documentId}:${content}:${lawyerSignature}:${timestamp}`;
  return createHash('sha256').update(hashInput).digest('hex');
}

/**
 * Generate verification URL for QR code
 */
export function generateVerificationUrl(documentId: string): string {
  // Use production URL or fallback to localhost for development
  const baseUrl = typeof window !== 'undefined' 
    ? `${window.location.protocol}//${window.location.host}`
    : 'https://sakshi.ai';
  return `${baseUrl}/verify?id=${documentId}`;
}

/**
 * Generate QR code data URL for PDF embedding
 */
export async function generateQRCodeDataUrl(
  documentId: string,
  size: number = 100
): Promise<string> {
  const verificationUrl = generateVerificationUrl(documentId);
  try {
    const dataUrl = await QRCode.toDataURL(verificationUrl, {
      width: size,
      margin: 2,
      errorCorrectionLevel: 'M'
    });
    return dataUrl;
  } catch (error) {
    console.error('QR code generation failed:', error);
    throw error;
  }
}

/**
 * Add verification section with QR code and hash to PDF
 * This should be called after all pages are generated
 */
export async function addVerificationSection(
  doc: jsPDF,
  documentId: string,
  blockchainHash: string,
  pageWidth: number,
  pageHeight: number,
  margin: number
): Promise<void> {
  const qrSize = 40;
  const qrX = pageWidth - margin - qrSize;
  const qrY = pageHeight - margin - qrSize - 5;

  try {
    // Generate QR code
    const qrDataUrl = await generateQRCodeDataUrl(documentId, qrSize);
    
    // Add QR code to PDF
    doc.addImage(qrDataUrl, 'PNG', qrX, qrY, qrSize, qrSize);
    
    // Add hash text below QR code
    doc.setFontSize(7);
    doc.setTextColor(100, 100, 100);
    const hashText = `Hash: ${blockchainHash.substring(0, 16)}...`;
    doc.text(hashText, qrX + qrSize/2, qrY + qrSize + 3, { align: 'center' });
    
    // Add verification text
    doc.setFontSize(8);
    doc.text('Scan to verify', qrX + qrSize/2, qrY - 2, { align: 'center' });
    
    doc.setTextColor(0, 0, 0);
  } catch (error) {
    console.error('Failed to add verification section:', error);
    // Fallback: just add text hash
    doc.setFontSize(8);
    doc.setTextColor(100, 100, 100);
    doc.text(`Document Hash: ${blockchainHash.substring(0, 24)}...`, pageWidth - margin, pageHeight - margin, { align: 'right' });
    doc.setTextColor(0, 0, 0);
  }
}

/**
 * Generate signed PDF with blockchain verification
 * This is an async version that includes QR codes
 */
export async function generateSignedPDF(
  content: string,
  title: string,
  documentId: string,
  lawyerSignature: string,
  options: PDFOptions = {}
): Promise<Blob> {
  const {
    font = "helvetica",
    fontSize = 14,
    lineHeight: customLineHeight
  } = options;

  // Generate blockchain hash
  const timestamp = new Date().toISOString();
  const blockchainHash = generateDocumentHash(
    documentId,
    content,
    lawyerSignature,
    timestamp
  );

  const doc = new jsPDF();

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const contentWidth = pageWidth - 2 * margin;

  let pageNumber = 1;
  const totalPages: number[] = [];

  // Calculate line height
  const lineHeight = customLineHeight || (fontSize * 0.5);
  const headerFontSize = fontSize + 4;
  const bodyFontSize = fontSize;
  const subHeaderFontSize = fontSize + 2;

  // Header
  doc.setFont(font, "bold");
  doc.setFontSize(headerFontSize);
  doc.text(title.toUpperCase(), pageWidth / 2, margin + 10, { align: "center" });

  // Body text
  doc.setFont(font, "normal");
  doc.setFontSize(bodyFontSize);

  const lines = doc.splitTextToSize(content, contentWidth);
  let y = margin + 25;

  for (let i = 0; i < lines.length; i++) {
    // Check if we need a new page
    if (y > pageHeight - margin - 30) {
      totalPages.push(pageNumber);
      
      doc.addPage();
      pageNumber++;
      y = margin + 10;

      // Add header to new page
      doc.setFont(font, "bold");
      doc.setFontSize(subHeaderFontSize);
      doc.text(title.toUpperCase(), pageWidth / 2, margin, { align: "center" });
      doc.setFont(font, "normal");
      doc.setFontSize(bodyFontSize);
      y = margin + 15;
    }

    doc.text(lines[i], margin, y);
    y += lineHeight;
  }

  totalPages.push(pageNumber);

  // Add QR code and hash to all pages
  for (let i = 1; i <= pageNumber; i++) {
    doc.setPage(i);
    await addVerificationSection(doc, documentId, blockchainHash, pageWidth, pageHeight, margin);
    
    // Add page number
    doc.setFontSize(10);
    doc.text(`Page ${i} of ${pageNumber}`, pageWidth / 2, pageHeight - margin + 10, { align: "center" });
  }

  return doc.output("blob");
}
